import { createElement } from 'lwc';
import Fec_customerAdditionalInfoList from 'c/fec_customerAdditionalInfoList';

describe('c-fec-customer-additional-info-list', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-fec-customer-additional-info-list', {
            is: Fec_customerAdditionalInfoList
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});