public with sharing class FEC_MockupEndpoint {
    
    public static final String GET_CUSTOMER_LIST_ENDPOINT_MOCKUP = 'https://f2f6273c-2000-45e1-8efb-7d0ffb4e1961.mock.pstmn.io';
    public static final String EMEA_ACCOUNT_INQ_ENDPOINT_MOCKUP = 'https://1cbfbf4e-b6d7-46c7-9717-79036857f118.mock.pstmn.io';
    public static final String GET_APP_STATUS_ENDPOINT_MOCKUP = 'https://02c8f939-7fcd-4ee0-944b-26af46ecb5ca.mock.pstmn.io';
    public static final String GET_BILLED_TRANSACTION_ENDPOINT_MOCKUP = 'https://fa889db0-0d70-4ff0-a772-7a7fc2347c26.mock.pstmn.io';
    public static final String GET_CARD_BASIC_INFO_ENDPOINT_MOCKUP = 'https://a37ae5f8-78f8-46ca-9500-1b5bf2b9f492.mock.pstmn.io';
    public static final String GET_CARD_FINANCIAL_TRANSACTION_ENDPOINT_MOCKUP = 'https://9d19f455-8916-4c0f-873d-b9e022bcdc75.mock.pstmn.io';
    public static final String GET_CARD_PAYMENT_INFO_ENDPOINT_MOCKUP = 'https://0ad0dbbf-693f-473e-a8db-d69d703f19a2.mock.pstmn.io/CIF_CardInfo';
    public static final String GET_CARD_PLAN_INFO_ENDPOINT_MOCKUP = 'https://0ad0dbbf-693f-473e-a8db-d69d703f19a2.mock.pstmn.io/CIF_CardInfo';
    public static final String GET_CARD_SEC_INFO_ENDPOINT_MOCKUP = 'https://d7f82a1e-a770-41e5-a1ea-0d684a148359.mock.pstmn.io';
    public static final String GET_CUSTOMER_SALE_DISBURSE_INFO_ENDPOINT_MOCKUP = 'https://efd335c2-f883-4625-83c1-74ec1d81085d.mock.pstmn.io';
    public static final String GET_IPP_DETAIL_ENDPOINT_MOCKUP = 'https://5fea0f8e-afdd-4820-aead-2a9a1fef654e.mock.pstmn.io';
    public static final String GET_PAYMENT_INFO_ENDPOINT_MOCKUP = 'https://d5f058dd-9fcf-4479-9fdd-a66463dde620.mock.pstmn.io';
    public static final String GET_REWARD_ELIGIBILITY_ENDPOINT_MOCKUP = 'https://ac989dc3-34ec-4c62-98cf-54ea477582c2.mock.pstmn.io';
    public static final String GET_STATUS_ENDPOINT_MOCKUP = 'https://fa2dbdcc-9a32-4469-8fc0-d9ca8def9cdd.mock.pstmn.io/CIF_CardInfo';
    public static final String GET_UNBILLED_TRANSACTION_ENDPOINT_MOCKUP = 'https://82338791-908c-4531-95b3-3d8e5ab19fe7.mock.pstmn.io';
    public static final String GET_ADDRESSES_LIST_ENDPOINT_MOCKUP = 'https://3541590e-4fb6-48e7-9dba-5a3259e62dc5.mock.pstmn.io';
    public static final String GET_APPLICATIONS_LIST_ENDPOINT_MOCKUP = 'https://7eb0f748-8126-49f2-946b-61016266d9f8.mock.pstmn.io';
    public static final String GET_CONTACTS_LIST_ENDPOINT_MOCKUP = 'https://4c75f566-6635-45c2-b066-1b73036661d6.mock.pstmn.io';
    public static final String GET_CUSTOMER_INFO_BASIC_ENDPOINT_MOCKUP = 'https://ce03371a-6afd-46a0-a1f1-0729fbf4d334.mock.pstmn.io';
    public static final String GET_DIGITAL_ACCOUNT_STATUS_ENDPOINT_MOCKUP = 'https://87eaeec6-b7ab-4552-997b-6aa7b7e55628.mock.pstmn.io';
    public static final String GET_DOCUMENTS_LIST_ENDPOINT_MOCKUP = 'https://241aef91-9cc1-4b9c-9618-629c9b022c47.mock.pstmn.io';
    public static final String GET_RELATIVES_LIST_ENDPOINT_MOCKUP = 'https://4fe9b5aa-83ad-47f8-801a-eba4fd18faf3.mock.pstmn.io';
    public static final String UPDATE_CUSTOMER_BASIC_INFO_ENDPOINT_MOCKUP = 'https://0b78db69-eb98-4c57-9924-dc958e4388df.mock.pstmn.io/CIF_CustomerInfoUpdate';
    public static final String UPDATE_CUSTOMER_CONTACT_ENDPOINT_MOCKUP = 'https://0b78db69-eb98-4c57-9924-dc958e4388df.mock.pstmn.io/CIF_CustomerInfoUpdate';
    public static final String FEC_GET_CARD_TXN_ENDPOINT_MOCKUP = 'https://f0e1b845-8481-4ebd-8a89-5ca8452c4182.mock.pstmn.io';
    public static final String GET_PRODUCTS_LIST_ENDPOINT_MOCKUP = 'https://2585e1bc-373f-45b8-8b0b-d25f87bd6422.mock.pstmn.io/CIF_CustomerInfo';
  public static final String GET_MRC_INFO_ENDPOINT_MOCKUP = 'https://0b78db69-eb98-4c57-9924-dc958e4388df.mock.pstmn.io/MRC_Info';
  public static final String GET_ASSETS_LIST_ENDPOINT_MOCKUP = 'https://0b78db69-eb98-4c57-9924-dc958e4388df.mock.pstmn.io/CIF_LoanInfo';
  public static final String GET_APP_INFOS_ENDPOINT_MOCKUP = 'https://0b78db69-eb98-4c57-9924-dc958e4388df.mock.pstmn.io/cif_applicationhistory/GetApplicationHistory';
  public static final String ADD_IPP_ENDPOINT_MOCKUP = 'https://159f99a4-6074-434e-94d7-49cf48012dd6.mock.pstmn.io/AddIPP';
}