public without sharing class FEC_BatchCaseHandlingImportRow {
    @AuraEnabled public String caseIdSearch;
    @AuraEnabled public String routingAction;
    @AuraEnabled public String inputtedRemarks;
    @AuraEnabled public String assignmentId;
    @AuraEnabled public String assignmentRoutingAction;
    @AuraEnabled public String csD2CAssessmentType;
    @AuraEnabled public String csSupportAssessment;
    @AuraEnabled public String riskLevel;
    @AuraEnabled public String requiredAction;
    @AuraEnabled public String classificationByCS;
    @AuraEnabled public String evaluationByCS;
    @AuraEnabled public String finalProduct;
    @AuraEnabled public String csD2CAssessmentTypeApiValue;
    @AuraEnabled public String riskLevelApiValue;
    @AuraEnabled public String requiredActionApiValue;
    @AuraEnabled public String classificationByCSApiValue;
    @AuraEnabled public String evaluationByCSApiValue;
    @AuraEnabled public String finalProductApiValue;
    @AuraEnabled public String recordId;
    @AuraEnabled public String status;
    @AuraEnabled public String errors;
}